### ISSUE TITLE
[年末用]今年買って良かったものBest3

### ISSUE THREAD

**Issue by shyaginuma** [geek-engineer-future/podcast#14]
## テーマ（ざっくりとしていてもOK！）
今年買って良かったものBest3

## appendix
Youtuberみたいだな

**Comment by takapy0210** [comment]
- ①ドラム式洗濯機
- ③スマートスピーカー
- ②FlexiSpot 電動昇降デスク
- モニター&モニターアーム
- イヤホン
- STEM BACKPACK CORDURA COATED BLACK

**Comment by shyaginuma** [comment]
- 電動キックボード
- Tシャツ
- チラシ・勧誘印刷物の無断投函は一切お断り！ 高耐候性ステッカー
- Airpods Pro
-
